//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPerson
    {
        public int GroupMemberNo { get; set; }
        public int GroupMemberPersonNo { get; set; }
        public int GroupNo { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
