//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPersonType
    {
        public int GroupPersonTypeNo { get; set; }
        public string GroupPersonTypeDesc { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
