//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonNo { get; set; }
        public int PersonTypeNo { get; set; }
        public int IdTypeNo { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int GenderNo { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
