//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkNo { get; set; }
        public string WorkDesc { get; set; }
        public int WorkTypeNo { get; set; }
        public int GroupNo { get; set; }
        public int PersonNo { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime SystemDate { get; set; }
    }
}
