//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkNo { get; set; }
        public string WorkDesc { get; set; }
        public Nullable<int> WorkTypeNo { get; set; }
        public Nullable<int> GroupNo { get; set; }
        public Nullable<int> PersonNo { get; set; }
        public Nullable<System.DateTime> GroupNameStartDate { get; set; }
        public Nullable<System.DateTime> GroupNameEndDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
