//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPersonResult
    {
        public int WorkPersonResultNo { get; set; }
        public int WorkNo { get; set; }
        public int PersonNo { get; set; }
        public int ResultNo { get; set; }
        public int ResultType { get; set; }
        public System.DateTime SystemDate { get; set; }
    }
}
